repos:
  - repo: local
    hooks:
      - id: usort
        name: Import sorter
        entry: bash -c 'usort format "$@"; git add -u' --
        language: python
        files: \.py$

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: black
        name: Formatter
        entry: bash -c 'black -l 79 "$@"; git add -u' --
        language: python
        files: \.py$
